import Config from 'react-native-config';

export const CONFIG = {
  TWITCH_CLIENT_ID: Config.TWITCH_CLIENT_ID!,
  TWITCH_AUTH_URL: Config.TWITCH_AUTH_URL!,
  REDIRECT_URI: Config.REDIRECT_URI!,
  TWITCH_WS_URL: Config.TWITCH_WS_URL!,
  DONATIONALERTS_AUTH_URL: Config.DONATIONALERTS_AUTH_URL!,
  DONATIONALERTS_CLIENT_ID: Config.DONATIONALERTS_CLIENT_ID!,
};
